---
title: "velociraptor sanity check"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "png", dev.args = list(type = "cairo-png"))
```

# Load packages

```{r}
suppressPackageStartupMessages({
    library(scRNAseq)
    library(scuttle)
    library(scran)
    library(velociraptor)
    library(scater)
    library(cowplot)
    library(GGally)
    library(reticulate)
    library(SingleCellExperiment)
    library(basilisk)
})
```

# Define virtual environment to use for reticulate

We use the `velociraptor` conda environment in order to run the scVelo commands also directly in python.

```{r}
reticulate::use_virtualenv(basilisk:::.obtainEnvironmentPath(velociraptor:::velo.env))
sys <- reticulate::import("sys")
sys$version
```

```{r}
py_config()
```

```{bash, results = "markdown", collapse=FALSE, message=FALSE, warning=FALSE}
echo $PATH
echo "working from the terminal"
```

```{python}
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```

# Session info

```{r}
sessionInfo()
```

